[build]
    publish = '.next'
    command = 'npm run build'

[[redirects]]
    from = '/odb/*'
    to = '/.netlify/builders/:splat'
    status = 200

[[redirects]]
    from = '/*'
    to = 'https://docs.netlify.com/:splat'
    status = 200
    force = true

[[plugins]]
    package = '/plugins/netlify-plugin-combined-sitemap'
