[[redirects]]
  from = "/home/*"
  to = "https://netlify-se-demo-portal.netlify.app/:splat"
  status = 200
  force=true


[[redirects]]
  from = "/home"
  to = "https://netlify-se-demo-portal.netlify.app/"
  status = 301
  force=true

