
[[redirects]]
  from = "/archive/*"
  to = "http://www.naturephotoblog.com/archive/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/test/*"
  to = "http://www.naturephotoblog.com/news/:splat"
  status = 200
  force = true

[[redirects]]
  from = "*"
  to = "http://www.naturephotoblog.com/:splat"
  status = 200
  force=true
