[build]
    publish = '.next'
    command = 'npm run build'

[[redirects]]
    from = '/odb/*'
    to = '/.netlify/builders/:splat'
    status = 200

[[redirects]]
    from = '/*'
    to = 'https://kaleidoscopic-palmier-4d744b.netlify.app/splat'
    status = 200