
[[redirects]]
  from = "/category/*"
  to = "https://www.photographyblog.com/category/:splat"
  status = 200
  force = true



[[redirects]]
  from = "*"
  to = "https://www.photographyblog.com/:splat"
  status = 200
  force=true
